deployments:
  environmentMapping:
    development:
      - "DEV-*"
      - "MKTP-*"
      - "JIRA-PROJECT-PREFIX-*"
    testing:
      - "testing"
      - "test"
    staging:
      - "staging"
      - "stg"
      - "homolog"
    production:
      - "production"
      - "prod"
      - "prd*"
