#on:
#  push:
#    branches:
#      - staging

on:
  pull_request:
    types: [opened]
    branches:
      - staging

name: Push test staging
concurrency: deploy-staging

env:
  HEROKU_APP_NAME: staging-cr

jobs:
  deployment:
    environment:
      name: "staging-teste"
      url: https://stagingcr.com.br
    runs-on: ubuntu-latest

    steps:
      - name: Deploya para staging (passou?)
        run:
          cat > ~/.netrc <<EOF

#
#      - name: Add staging remote to git
#        run: git remote add staging https://git.heroku.com/${HEROKU_APP_NAME}.git
#
#      - name: Push master branch to Heroku
#        run: git push -f staging master:master